#+STARTUP: indent
#+TITLE: 有关点云的一些内容
#+AUTHOR: Reader

* 一些传统的几何特征
** PFH - Point Feature Histogram
** FPFH - Fast Point Feature Histogram
** SHOT - Signature of Histograms of OrienTations
在其论文里，明确了Local Reference Frame的关键作用及标准处理方式。
** ISS - Intrinsic Shape Signatures
** TOLDI - Triple Orthogonal Local Depth Images
改进了Local Reference Frame的处理方式。
** SDF - Shape Diameter Function
** AC - Ambient Occlusion
** AGD - Average Geodesic Distance
** SuperPoint,尽管是Image上的工作,其基于Homograhic Adaption的Self-Supervised Learning是值得思考的.
* PointNet &. PointNet++ & PointMLP:
** 怎么理解"Point Based Method" for Point Cloud Anylasis!
没有转换成其他几何结构(如: Voxel等)!
** PointNet
针对Spatial Point Set的几个特性:
- Unordered
- Interaction Among Points(例: with a distance metric)
- Invariant under transformation
提出解决方案:
- Symmetric Function For Unordered Points:
  所谓的对称函数，采取了集合函数的形式。关键是他那个集合函数有什么性质？(Point Set Abstraction By FPS and KNN?)
  - Universal approximate. 欧式空间幂集上的函数是对称函数,但要解决的理论问题是,在欧式空间幂集上如何定义度规?
  - To summarize a shape by a sparse set of critical point. 这倒是要理解一下.
- Local And Global Information Aggregation
- Joint Alignment Networks
** PointNet++
PointNet++认为PointNet缺少一种能力: 在不同尺度下,扑捉局部上下文(To capture local context at different scales!)
How to capture local context?(略!)
** PointMLP
...we show case that even without the carefully designed operations for local geometry exploration,
a pure deep hierarchical MLP architecture is able to exhibit gratifying performances and even better results...
==> deep residual mlp for point cloud.
如何结束在局部"几何"的竞争?而转入全局探索的道路!但什么是全局关系?
* 基于深度学习的特征点学习
** 3DSmoothNet
利用的基础技术
- LRF - Local Reference Frame
  局部参考标架,这是必备的预处理了。
- SDV - Smoothed Density Value Voxelization
  这是较特殊的局部统计方式。
- Batch Hard(BH)
  这要参考[In Defense of the Triplet Loss for Person Re-Identification]中的内容了。
  此文在Siamese/Triplet架构里,算是名文了。
** SpinNet vs. DIP vs. GeDi 可能要比对看一下, Descriptor如何获取.
* 配准
** Teaser[++] 值得研究一下.
** GeoTransformer
** Greed Grid Search
* 稀疏卷积
这应当是微妙的话题!人们过多地关注了计算效率,并未分析"稀疏"的本质!
- MinkowskiEngine
- TorchSparse, Torchsparse++
- SpConv Spconv2
* Position Embedding in PointCloud
绞尽脑汁的玩意儿.所谓的启发式,其实很多是想当然的!
位置信息(如果放到空间认知这个范畴来讨论的话),应当说,完全是个没有澄清的概念!
- 绝对位置编码
- 相对位置编码
  - 在Point Cloud的领域,有很多RPE的工作!比如V-Detr里,3DV-RPE是其主要贡献!
  - 另有[MicroSoft]2021 - iRPE - Rethinking and Improving Relative Position Encoding for Vision Transformer的工作,
    对早期的Point Transformer一线的工作有更多的影响!
- 条件位置编码
  [2021 - CPE - CPVT - Conditional Positional Encodings for Vision Transformers - v3]
  这是ViT领域里的一项工作.但Point Cloud Transformer领域里,常有人借用其思想!
  如PTv3一脉的工作,用SPCONV就得到了xCPE!
* Point Cloud Transformer 哪家强?
按时间次序,依次为:
- [Nico Engel]2021 - Point Transformer  --(1)
- [Guo M.H.]2021 - PCT - Point Cloud Transformer  --(2)
- [Zhao H.S.]2021 - Point Transformer  --(3)
应当是有答案了,一直在往下作的,是HKU的团队,即(3)的作者们!!!
** "Point Transformer v3",这篇可能要细看了!
*** 应当关注PointCept名下的一系列的工作!!!
*** Scaling Principle:
有些模糊理解.应当指"Uitilizing multi-dataset joint training stratgies"
模型的性能中,有个"accuracy vs efficiency"的权衡问题.
*** Breaking the curse of permutation invariance:
这个可能更重要, ~Serialization-based method.~
** PTV3的后继工作"Sonata"
有关"Zero/Few Short"式的点云预训练模型,为什么进展缓慢?
"Sonata"的工作,揭示了在3D SSL领域中,存在"Geometric ShortCut"问题! -- 有意思!
- 学到的"Features Representation",容易塌缩到"low-level spatial features"
* Space is sequences
这是一个有意思的话题.应当从感知的角度,来看待此问题!
背后的本质问题是集合的结构化的道路!既要反应局部,又要反应全局互通!!!
** MeshWalker
** CurveNet
* Learned Query in PointCloud
[2022 - SPFormer - Superpoint Transformer for 3D Scene Instance Segmentation]
[2023 - Mask3D - Mask3D for 3D Semantic Instance Segmentation]
[2023 - OneFormer3D - One Transformer for Unified Point Cloud Segmentation]
* KeyPoints or LandMark(or LandScape) or Pose in PointClouds
事实上,这是一个困难的领域！
** 先看看Image领域的!
[2024 - X-Pose - Detecting Any Keypoints]
[2024 - XPose - eXplainable Human Pose Estimation]
[2024 - Unsupervised Keypoints from Pretrained Diffusion Models]
[2023 - Detecting Arbitrary Keypoints on Limbs and Skis with Sparse Partly Correct Segmentation Masks]
还有[TokenPose],[VitPose],[TransPose](这几个都是利用Transfomer得到Heatmap)等等,还是很多的！
看到很多方法,从FeaturePoint这种孤立地观点,到Pose这种有内在结构关联的观点,怎么搞出比较好的"关键点"定义!
** 一个小问题, keypoint/featurepoint descriptor和keypoint/featurepoint detector的区别！
*** [2019 - USIP: Unsupervised Stable Interest Point Detection from 3D Point Clouds]
作者的前期工作, [2018 - SO-Net - Self-Organizing Network for Point Cloud Analysis].
USIP应当是个先锋,作为基于学习的3d关键点检测方法,远超传统方法.
有关descriptor的文章多,而detector的内容少!
由于容易获得GroundTruth(这和Registration Task相关),基于深度学习的descriptor,有比较好的发展!
这篇文章的想法好像深刻,其实很原始!-学习变化不变量-.
不变量,能否全面反映"点云的结构".
*** keypoint detection 和 keypoint estimation 又有什么区别？
文章[2023 - 3D Keypoint Estimation Using Implicit Representation Learning]作了一些澄清!
点->小球面, 定义DeepSDF,学它,用Marching-Cube来估计!
*** 点云的结构(Structure of Point Cloud)和关键点
点集/点云/等,所代表的对象/空间的结构其实是个关键问题
结构表面上是个清晰的概念,但在点云的世界里,却是非常难以定义的概念或内容！
**** 关键点这个概念,在几个方面使用:
- 其一是有明确指认意义上的语义. ?KeyPoint
- 其二是在重构、生成、完形上的指导语义. ?Salient Point
  潜意识里,结构或许是由"关键点"作为基本基石,但在无监督情况下,如何生成"关键点",以便保证"结构"的关键信息.
  不能是几个指认的关键点,因为它们只含有稀疏的语义信息！
  这是一条研究线路！充斥着较多的无监督名义下的学习方法!
- 其三是和feature point合流. ?Feature Point
**** [2022 - PointSCNet: Point Cloud Structure and Correlation Learning Based on Space Filling Curve Guided Sampling]
2022写的,2024才有正式的发表!
比PTV3较早地利用SFC作结构性描述!
利用SFC构造统一的参考结构！
**** [2021 - Skeleton Merger - an Unsupervised Aligned Keypoint Detector]
......
[2024 - Key-Grid - Unsupervised 3D Keypoints Detection using Grid Heatmap Features]
这一系列的工作
** Points In/By Points
实质上这里有很多自然"人性"的原因!总感觉,是想当然,是"点线面"的自然想法!?
*** Points In Points
Feature Point, KeyPoint, Superpoint, (Random) Sampled Points
*** Points By Points
怎么说,以各种方式定义构建"最优"参考点,来获得"表示"!(相对位置编码可能也在此列!)
* 连续性表示(如SDF)/或隐涵性表示,及相关的下游任务!!
** SDF(Signed Distance Function)
- [2025 - PartSDF - Part-Based Implicit Neural Representation for Composite 3D Shape Parametrization and Optimization]
- [2023 - 3DShape2VecSet - A 3D Shape Representation for Neural Fields and Generative Diffusion Models]
  为了生成的目的,在Latent Space作SDF工作.而且,我看到它的网络结构,很容易想起Perceiver!
  本文要解决的问题是,在作者们的前期工作3DILG中,Latent Space对样本坐标空间的显示依赖!
  注意,他是为了生成的目的.
- [2023 - 3D Keypoint Estimation Using Implicit Representation Learning]
  构造了一个奇怪的SDF,关键点用包含它的球面来估计,问题就变成学到这种隐涵的表示!.文章中,“相关工作”一段的辨析,比较好!
- [2022 - SNAKE - Shape-aware Neural 3D Keypoint Field]
  作者在探索一个问题:"Whether jointly reconstructing underlying 3D shapes helps 3D keypoint detection!"
** VecSet/VoxSet在3D生成中,似乎很受器重!
3D SDF可以由某Set来表示,这很神奇!
- VecSet的简史
  3DShape2vecset -> Dora-Vae CraftsMan3D-Vae -> COD-Vae
- VoxSet的简史
  XCube(Sparse Voxel Hierarchies)
  -> Trellis(SLAT:Structured LATents)
  -> Ultra3D(Part-Attention, Global VecSet & Local SLAT?, VecSet-based Sparse Voxel Generation?)
  -> Lattice(VoxSet)
* Topology Data Analysis(TDA)和Geometric Data Analysis(GDA)
* 3D Representation Learning
** [2024 - 3D Representation Method: A survey]可以看看.虽然新,但目前来看,总结得不到位,提供的资料也不全!
* 3D Object Detection with Detr-Base Method
[...Voting Based Method,Expansion Based Method,Detr-Based Method...]
Detr-Based Method没怎么跟踪,现在从下面几篇文章开始,了解一下现状!
(Detr下的关键话题:Learnable Query,Hungarian Matching,Loss Formulation)
(怎么看, Detr-Based Method的基础模式有点类似 BackBone + Perceiver???!!!)
- [2025 - DEST - State Space Model Meets Transformer - A New Paradigm for 3D Object Detection]
  奇怪的范式!
- [2024 - UniDet3D - Multi-dataset Indoor 3D Object Detection]
  减法怎么被他玩动了呢?实质上是偏离了DeTr-Based Method的基线(BaseLine)!
  Superpoint + Transformer Encoder!
- [2023 - V-DETR - DETR with Vertex Relative Position Encoding for 3D Object Detection]
  在3D检测领域,让基于DeTr的模型的性能不再落后其他路线的模型!
  V-DeTr 和 GroupFree3D形成了这个方法系列的基线?!
  应该是在GroupFree3D和3DETR的基础上作的!
  这篇文章传达的信息:
  - 3DV-RPE:相对位置编码体现了什么?这被认为本文的主要贡献！
  - Decoder的Queries输入,该怎么构造,或初始化!
* 3DVG(也叫做3D instance reference),稀疏卷积是不是一个方向？
[2025 - TSP3D - Text-guided Sparse Voxel Pruning for Efficient 3D Visual Grounding]
首先要明白Instance Reference和Object Detection的区别与联系！
