
#+STARTUP: indent
#+TITLE: NeuralNetwork 阅读纪要

* 概要
对于这些年的盲目阅读，很难给出一个合乎逻辑的条理来。
但一直以来，围绕着Retinotopy（Tonotopy 从没关注过）的Functional Architecture, Computational Model, Biology Origin等，隐含地关注着一下几个主题方面：
- Retina-LGN的感受野的非线性结构。以Saccade/Microsaccade为线索，引出来的一系列问题！
- LGN-Cortex的稀疏问题。LGN供给Coretex的输入是非常稀疏的，却能产生极其复杂的。。。！这意味着什么？
- The Functional Architecture of The Visual Cortex的形成机理？和Orientation Maps的起源！
- Cortex的Column/Microcolumn结构的一般化问题。
- 在Perceptual Grouping问题下，思考association问题。对NeuralGeometry这个小众的数学模型很着迷。

** Retina:Microsaccade and saccade.
1. [Field G.D. ;Chichilnisky E.J. ]2007-Information Processing in the Primate Retina
   总结了视网膜在神经生理学、解剖学上的新认知。
   - Many distinct pathways of visual information emanate from the retina.
     - 最早开端
       猫视网膜上的RGC(Retina ganglion cell)研究。
       生理学上发现了X(linear)/Y(nolinear) cell。解剖学上发现了alpha/beta cell。
       由是而有Two PathWay的研究主线。
       如，在灵长类的研究中，Midget（侏儒）/Parasol（伞状）cell投射到LGN的Parvocellular（小细胞的）/Magocellular（大细胞的）层，继而投射到视觉新皮层。
       这两条路径，占据了各项研究的主角。
     - Small Bistratified RGC的发现。
       Small Bistratified Cell投射到LGN的Koniocellular（粒状细胞的）层，继而投射到视觉新皮层的路径又多了一条。
       至此，这三条路径，构成了目前教科书的主要内容。太简化问题了！
     - 但近来，还发现更多的新RGC类型,及更多的投射路径。
       按形态来划分，并合并On/Off子类，如：
       - Momostratified: Midget/Parasol/Sparse/GiantSparse/Recursive/Smooth/BroadThomy/Thomy
       - Bistratified: Recursive/Large/Small
       等RGC类型，共产生了11条到LGN的路径。
       此外，还有些RGC，产生了到Superior colliculus（上丘）及其他Nonthalamic structure的投射路径。
       许多RGC还会投射到至少两个中央结构的投射路径。
     - 不寻常的视觉信号（Novel visual signals）
       令人惊讶的是，这些新发现的RGC的生理特性并不是很清楚。
     - 视觉路径的多样性，发端于视网膜内。（Intra-retina origins of diversive visual pathways）
       =在视网膜内的线路中解释多样性。（Interpretation of diversity in rentina circuits）=
     - 影响（Implication）：
       对视网膜的研究：
       对视觉系统的研究：The visual signals emanating from multiple distinct RGC types may remain segregated in the cortex!也就是有多种信号进入新皮层!
       对大脑的研究：脑皮层里Cell-Type diversity可能有待大发现!

   - Precesion OF Retinal Spike Trains And Models Of The Neural Code.
     Nonlinear spatial-temporal integration encoding成了新认识！
     Many common biophysical phenomena, such as refractoriness, bursting, spike frequency adaptation, and oscillation, give rise to intrinsic temporal structure in spike trains.
     Thus,to understand how neural circuits process and represent information generally requires measurements and models that *go beyond descriptions of firing rate*.

   - Synchronized firing and consequences for visual signaling
     The significance of synchronized firing and other patterns of multineuron activity is a fundamental problem in many neural circuits.
     The structure of synchronized firing in RGCs —regularity, spatial locality, and cell-type specificity— may provide clues about other neural structures.
   - Decoding the visual signal from retina spike trains

   - Conclusions
     - At the photoreceptor synapse, multiple distinct visual signals begin to emerge.
     - These signals are processed by a diverse collection of bipolar and amacrine cell types that converge on at least 17 distinct types of RGCs, each of which covers the visual field with striking regularity.
2. [Rolfs M.]2009 - Microsaccade - Small steps on a long way
   [Rucci M.;Ahissar E.;Burr D.]2018 - Temporal Coding of Visual Space
   Mircrosaccade对visual signaling究竟有什么本质的影响？
3. 可以细读[Gollish T.;...]2010 - Eye Smarter Than Scientist Believed。
4. [Schwartz G.W.]2012 - The spatial structure of a nonlinear receptive field
   =Two features= of spatial integration in RGCs presents major obstacles for a predictive model: nolinearity and fine-scale heterogeneity.
   =Model based on anatomical and physiological mechanisms=
   Their *anatomically* based model captured the response profiles of individual RGCs more closely than previous receptive-field models based on linear spatial integration or a Gaussian weighting of nonlinear subunits.
   附注：Schwartz G.W.的后期工作，尽管不是retina方面的，也还值得关注。他基于图论，一直在作Anatomically based model的工作。
   Fred Rieke就是写Spike那本书的作者，其实验室的工作更值得关注。
   1. [Schwartz G.W.]2011 - Nonlinear spatial encoding by retinal ganglion cells_ when 1 + 1 ≠ 2
5. [Gollisch T.;...]2013 - Features and functions of nonlinear spatial integration by retinal ganglion cells
   概述了鉴别Nonlinear signal integration的各类方法、途径。
   最后回到他们自己的ISO-Reponse方法。
   不需要太深的解剖细节，就能评价非线性集成的方式!
   4和5两篇，对subfields/subunits LN的推动比较大。
   *Iso-response measurements represent an alternative, as they provide a way to assess nonlinear stimulus integration without the need of an a priori parameterization of the nonlinearities.*
6. [Martinez-Conde S.]2013 - NRN - The impact of microsaccades on vision
7. [Real E.;Asari H.;Golish T.;Meister M.]2016 - Neural Circuit Inference from Function to Structure
   有趣的话题，基于模型，将Circuits推断出来！
8. Tuturial - Statistical Models for Neural Data: from Regression / GLMs to Latent Variables - Pillow J.W. - 2016
   [Pillow J.W.]2008 - Spatio-temporal correlation and vision signalling in a complete neuronal population
   事实上，从2008这篇文章开始，Pillow的工作，就集中在 *How does the spiking activity of a neural population represent the sensory environment?*
9. [Shah N.P.;Simoncelli E.;Chichilnisky E.J.]2020 - Inference of nonlinear receptive field subunits with spike-triggered clustering
   [Liu J.K.;...]2017 - Inference of neuronal functional circuitry with spike-triggered non-negative matrix factorization
   [Freeman J.;....]2014 - Mapping nonlinear receptive field structure in primate retina at single cone resolution
   [Field G.D.;Chichilnisky E.J.]2010 - Functional connectivity in the retina at the resolution of photoreceptors
   ......
   这其实Simoncelli E. Chichilnisky E.J.宗派的系列文章。
信号的多样性、信号激励的非线性整合的多样性，是这些故事的内容。
视网膜的故事,最终引向这句话:Subunits appear to be a common computational motif in the brain.
但带来的问题: Encoding and decoding in a heterogeneous population!
** Visual Neocortex
* Place Cells/Grid Cells/Head Cells/Border Cells/Speed Cells/Trace Cells/Object Cells/Object vector Cells, and so on
观看视频"Grid Cells, Object Representations, and Memory" & "Grid Cells and the Brain's Spatial Mapping System"
Memory is a process reproduce/reconstruction!? (David Marr)
Navigation is the core!?

* [Bicanski A.;Burgess N.]2019 - A Computational Model of Visual Recognition Memory via Grid Cells

* [Stensola T.;Moser E.I.]2016 - Grid Cells and Spatial Maps in Entorhinal Cortex and Hippocampus
It's a review!
** Place Cells and Grid Cells神经生理发现
- Place Cells:  ... Tolmanian cognitive maps
- Grid Cells: ...
** Grid-to-Place Transformation中的神经生理
Grid Map的组织方式: 沿着 MEC 的 DorsalVentral Axis 的 Modular Organization. See "Discretization of the Entorhinal Grid Map"
** Computational Models Of Grid-to-Place Transformation
一堆的猜想，留待慢慢阅读吧？
* New approaches to Deep Networks
这是一篇评论，议及四种网络
- CapsuleNet  (Hinton  @ ??)
- HTM         (Hawkins @ Numenta)
- Sparsey     (Rinkus  @ Neurithmic Systems)
- RCN         (George  @ Vicarious)

References
- Sabour, S., Frosst, N. & Hinton, G.            Dynamic Routing between Capsules. (2017).
- Hawkins, J., Ahmad, S. & Cui, Y.               Why Does the Neocortex Have Layers and Columns, A Theory of Learning the 3D Structure of the World.(2017).
- George, D. & Hawkins, J.                       A hierarchical Bayesian model of invariant pattern recognition in the visual cortex.(2005).
- Hawkins, J. & George, D.                       Hierarchical temporal memory: Concepts, theory and terminology.(2006).
- George, D. & Hawkins, J.                       Towards a mathematical theory of cortical micro-circuits.(2009).
- Hawkins, J., Ahmad, S. & Dubinsky, D.          HTM Cortical Learning Algorithms.(2011).
- Hawkins, J. & Ahmad, S.                        Why neurons have thousands of synapses, a theory of sequence memory in neocortex.(2016).
- George, D. et al.                              A Generative Vision Model that Trains with High Data Efficiency and breaks text-based CAPTCHAs.(2017).
- Rinkus, G. J.                                  A cortical sparse distributed coding model linking mini- and macrocolumn-scale functionality.(2010).
- Rinkus, R. & Leveille, J.                      Superposed Episodic and Semantic Memory via Sparse Distributed Representation. (2017).

* Sparsey - Event Recognition Via Deep Hierarchical Sparse Distributed Code - 2014
注：在《Radically New Theory of how the Brain Represents and Computes with Probabilities》里又总结了他的那些激进理论。
A macro/mini-column model of cortical computation
cells -> mini-columns (competitive modulars) -> macro-columns

作者反思群编码的问题：
Most previous probabilistic population coding (PPC) theories share basic properties:
1) continuous-valued units;
2) fully/densely-distributed codes;
3) graded synapses;
4) rate coding;
5) units have innate unimodal tuning functions (TFs);
6) units are intrinsically noisy;
7) noise/correlation is generally considered harmful.

They present a radically different theory that assumes:
1) binary units;
2) only a small subset of units, i.e., a sparse distributed representation (SDR) (a.k.a. cell assembly, ensemble),comprises any individual code;
3) functionally binary synapses;
4) signaling formally requires only single(i.e., first) spikes;
5) units initially have completely flat TFs (all weights zero);
6) units are far less intrinsically noisy than traditionally thought;
7) rather noise is
   - a resource generated/used to cause similar inputs to map to similar codes,
   - controlling a tradeoff between storage capacity and embedding the input space statistics in the pattern of intersections over stored codes,
   - epiphenomenally determining correlation patterns across neurons.

* RCN - Recursive Cortical NetWork
RCN integrates and builds upon various ideas from Compostional Models - ... - into a structured probabilistic graphical model such that Belief-Propagation can be used as the primary approximate inference engine.

* HTM(Hierarchical Temporal Memory)
(目前,有这种理论变化 HTM => The Thousand Brains Theory of Intelligence)
** Biological and Machine Intelligence: - A digital book that documents Hierarchical Temporal Memory (HTM) - 这里面可能真有戏!
这是关于HTM的技术文档。
*** HTM Principles
神经生理学上的那些内容，启发了作者的基本原理？
- Biological Observation: =The Structure of the Neocortex=
  HTM principle:          =Common Algorithms [Cellunar layers - Mini-Columns - Columns]=
- Biological Observation: =Neurons are Sparsely Activated=
  HTM principle:          =Sparse Distributed Representations(SDR)=
- Biological Observation: =The Inputs and Outputs of the Neocortex=
  HTM principles:
  1. Sensory Encoders
  2. HTM Systems are embeded within sensory-motor Systems
  3. HTM relies on streaming data and sequence memory
  4. On-Line learning
*** Sparse Distributed Representations
- Capacity of SDRs and the probability of mismatches
- Robustness of SDRs and the probability of error with noise
- Reliable classification of a list of SDR vectors
- Unions of SDRs
- Robustness of unions in the presence of noise
*** Encoding Data for HTM Systems
*** Spatial Pooling algorithms
*** Tempory Memory Algorithms
*** Voting across columns
*** Location Layers in Grid Cells
** 几篇论文：
*** Why neurons have thousands synapses - a Theory of Sequence Memory in Neocortex [Hawkins J]2015
建立了 HTM model neurons.
*** The HTM Spatial Pooler — A Neocortical Algorithm for Online Sparse Distributed Coding [YuWei Cui]2017
*** 关于Location Based FrameWork的思想的形成，目前看三篇文章:
- =A Theory of How Columns in the Neocortex Enable Learning the Structure of the World [Hawkins J.]2017=
  Columns and Layers 是个通用结构,这意味着什么?
- =Locations in the Neocortex - A Theory of Sensorimotor Object Recognition Using Cortical Grid Cells [Lewis M.]2019=
- =A Framework for Intelligence and Cortical Function Based on Grid Cells in the Neocortex [Hawkins J.]2019=
  这篇文章提出了Location Based Framwork的思想.
* The Origins of Orientation Maps in V1
Neural tuning to visual stimulus orientation is one of the hall-marks of the primary visual cortex (V1) in mammals.
= The orientation map is a hallmark of primary visual cortex in higher mammals.
** Retina - Thalamus - Cortex
The Orientation map的形成机理,......
A key assumption of the current model is that neighboring V1 neurons receive feedforward inputs from a similar population of nearby RGCs, as suggested by the statistical wiring model.
见[Ringach D.]的2004，2007的文章。
但这个模型没有直接的实验数据来作支撑，故引出些许争议。
1. [Schottdorf M.;...]2015 - Random Wiring, Ganglion Cell Mosaics, and the Functional Architecture of the Visual Cortex
   这篇文章用实验作比较研究，值得看完。可了解对V1 functional architecture的形成机理进行解释的各种假说，以及它们之间的争论！
   但此文似乎是在用数据，质疑最新的Statistics wiring model（如Moire Interference Model），因为它还是不能满足‘common design’的试验结果。
   'Common Design'这一概念来至"[Kaschube M.;...]2010 - Universality in the evolution of orientation columns in the Visual Cortex"。
   有两种相对立的形成机理假设模型
   1) Statistics wiring model。 Moire Interference Model是目前较简洁有效的模型。但是受到此文的温柔质疑。
   2) Long-Range interaction model。 Kaschube M.用这类模型中的SOM来解释他发现的Universality，即所谓的‘common design’。
   此二者也代表了Forward和Recurent的争论。
   至于结论，我们细看。
2. [Paik SB.;Ringach D.]2011 - Retinal origin of orientation maps in the visual cortex
3. [Paik SB.;Ringach D.]2012 - Link between orientation and retinotopic maps in primary visual cortex
   此二文，给出了 Origin of orientation maps 的 Moire Interference机理猜想。这个值得注意。
   同时将Origin问题，延伸到Retina。Retina Mosaics 近乎可确定 Orientation Map。
4. [Markram H.]2015 - Reconstruction and Simulation of Neocortical Microcircuitry
5. [Jang J.]2020 - Retino-Cortical Mapping Ratio Predicts Columnar and Salt-and-Pepper Organization in Mammalian Visual Cortex
   实验验证了V1面积/R面积，这样一个参数，可以推断 V1 Orientation Map的类型，连续的还是椒盐的。
   讨论出这样的观点：
   1) Firstly, seeded by forward afferents.
   2) Secondly, fine-tuned by various types of synaptic plasticity in feedfor-ward and recurrent circuits
* Neural Geometry and Group-CNN
Neural Geometry源自对 Visual Cortex Columns结构的理论解释。
我看它现在发展出Group-CNN路线，和Manifold learning、Geometric deeplearning、Graph deeplearning相结合。
